[project]
name = "preservation-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["piffle>=0.6.0", "smolagents>=1.0.0"]
